### ISSUE TITLE
\Wsdl2PhpGenerator\Generator reusage

### ISSUE THREAD

**Issue by red-led** [wsdl2phpgenerator/wsdl2phpgenerator#204]
```php
$config1 = [
    'inputFile' => 'in1.xml',
    'outputDir' => 'dir1',
....
];
$config2 = [
    'inputFile' => 'in2.xml',
    'outputDir' => 'dir2',
....
];
$generator = new \Wsdl2PhpGenerator\Generator();
$generator->generate(
        new \Wsdl2PhpGenerator\Config($config1)
);
$generator->generate(
        new \Wsdl2PhpGenerator\Config($config2)
);
```

After this ```dir2``` will contain all of ```dir1``` subclasses.

**Comment by kasperg** [comment]
Thanks for reporting this @red-led .

**Comment by sagikazarmark** [comment]
Is this because the context is somehow preserved between the two calls?

**Comment by kasperg** [comment]
@sagikazarmark: Yes. Some properties are not reset between calls to `generate()` e.g. [`$types`](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/Generator.php#L38).

**Comment by sagikazarmark** [comment]
@kasperg is this because of some sort of caching purposes?

Because in that case using a caching solution would be better IMHO instead of preserving the state in the generator. I am not suggesting to use a distributed caching system, but to use any of the awesome caching libraries out there which let's the developer choose the right tool (or fallback to an array cache).
